url: https://ebrelsford.github.io/portfolio
baseurl: /portfolio

# Site settings
title: Eric Brelsford
email: hi@ebrelsford.com
description: "Eric Brelsford, freelance map-maker and web developer with a passion for community-driven maps and data."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7DB89F
  secondary: 577C6D  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ebrelsford
  - title: github
    url: http://github.com/ebrelsford
  - title: youtube
    url: http://youtube.com/channel/UCsmBq4ziqRgBZSJK8sGF0Fg

# Postal address (add as many lines as necessary)
address:
  - line: Brooklyn, NY

# Build settings
markdown: kramdown
permalink: pretty
